
version: '3'
services:
  jakartaEE:
    build:
      args:
        - MINOR
        - GITHUBLOGIN
        - GITHUBPASSWORD
      context: .
      dockerfile: Dockerfile
    image: pcisse200/samplejee91:10
