
version: '3'
services:
  jakartaEE:
    build:
      args:
        - MINOR
        - GITHUBLOGIN
        - TAG
        - GITHUBPASSWORD
      context: .
      dockerfile: Dockerfile
    image: pcisse200/samplejee9100:${TAG:-latest}
