name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  MAJOR: ${{secrets.MAJOR}}
  MINOR: ${{secrets.MINOR}}
  
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    -
      name: Build the Docker image
      run: docker build --tag pcisse200/master-rep:${{ MAJOR }}.${{ MINOR }} .
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ DOCKERHUB_USERNAME }}
        password: ${{ DOCKERHUB_PASSWORD }}
  
