name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
  DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
  GITHUBLOGIN: ${{secrets.GITHUBLOGIN}}
  GITHUBPASSWORD: ${{secrets.GITHUBPASSWORD}}
  MAJOR: ${{secrets.MAJOR}}
  MINOR: ${{secrets.MINOR}}
  
jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    -
      name: Build the Docker image
      run: docker build --tag pcisse200/master-rep:${{ secrets.MAJOR }}.${{ secrets.MINOR }} .
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_PASSWORD }}
    -
      name: Push to DockerHub
      run: docker push pcisse200/master-rep:${{ secrets.MAJOR }}.${{ secrets.MINOR }}
    -
      name: Update Minor version
      uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: 'MINOR'
        value: $((${{ secrets.MINOR }}+1))
        repository: papemor94/ci-actions-test
        token: ${{secrets.GIT_TOKEN}}
