name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
  DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
  GITHUBLOGIN: ${{secrets.GITHUBLOGIN}}
  GITHUBPASSWORD: ${{secrets.GITHUBPASSWORD}}
  MAJOR: ${{secrets.MAJOR}}
  MINOR: ${{secrets.MINOR}}
  
jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Show minor
      run: echo ${{env.MINOR}}
    - name: Build the Docker image for branch ${GITHUB_REF_NAME}
      # run: DOCKER_BUILDKIT=1 docker build . --build-arg GITHUBLOGIN --build-arg GITHUBPASSWORD --build-arg SONAR_URL --build-arg SONAR_TOKEN --file ./docker/Dockerfile --tag brunoe/samplejee91:${GITHUB_REF_NAME}
      run: COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 BRANCH=${GITHUB_REF_NAME} TAG=${{secrets.MINOR}} docker-compose build jakartaEE
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Push to DockerHub Registry
      run: COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose push
